# Generated by Django 5.2.2 on 2026-08-19 12:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('population_hommes', models.IntegerField(blank=True, null=True)),
                ('population_femmes', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_etablissement', models.CharField(choices=[('poste_sante', 'Poste de santé'), ('centre_sante', 'Centre de santé'), ('hopital', 'Hôpital'), ('centre_medico_social', 'Centre médico-social'), ('pharmacie', 'Pharmacie')], max_length=30)),
                ('statut', models.CharField(blank=True, choices=[('public', 'Public'), ('prive', 'Privé')], max_length=10)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='sante.quartier')),
            ],
        ),
    ]
