# Generated by Django 5.2.2 on 2026-08-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etablissement',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='quartier',
            options={'managed': False},
        ),
    ]
