# Generated by Django 5.2.2 on 2026-08-21 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0002_alter_etablissement_options_alter_quartier_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='etablissement',
            table='etablissement_sante_test',
        ),
        migrations.AlterModelTable(
            name='quartier',
            table='yoff',
        ),
    ]
